### ISSUE TITLE
Is this getting merged with python-bittrex-websocket?

### ISSUE THREAD

**Issue by ackdav** [slazarov/python-bittrex-autosell#1]
Really a non-issue, but I didn't want to bother you via email...
Will you merge this with your python-bittrex-websocket library? I setup a little trading algo with python-bittrex-websocket, but am missing the trading functionality ;)  
So before spending hours researching - how would you go about trading on top of the data we can get with python-bittrex-websocket?
thx a lot!

**Comment by slazarov** [comment]
Hi, I prefer to keep them separate since they provide different functions and it’s easier to solve specific issues in this way. That’s at least until the socket reaches a stable version.

I’m on my phone right now but to get you started I would run the socket as it is and start a new thread for the auto sell in the main script.

**Comment by ackdav** [comment]
thanks @slazarov - appreciate it. I mainly miss the buy/sell ability in the socket. but separating the whole "autosell" function makes sense of course.
